export const SYSTEM_ROLE_KEYS = [
  "super_admin",
  "admin",
  "production",
  "sales",
  "distributor",
  "customer",
  "guest",
  "service",
] as const;

export type SystemRoleKey = (typeof SYSTEM_ROLE_KEYS)[number];

/** Permission keys are the authorization unit. Roles only bundle permissions. */
export const PERMISSION_KEYS = [
  "users:read",
  "users:invite",
  "users:update",
  "users:deactivate",
  "roles:read",
  "roles:assign",
  "roles:manage",
  "org:read",
  "org:update",
  "org_units:manage",
  "warehouses:manage",
  "api_keys:manage",
  "sessions:revoke",
  "sessions:read",
  "settings:read",
  "settings:update",
  "feature_flags:manage",
  "audit:read",
  "audit:export",
  "security:read",
  "alerts:read",
  "alerts:manage",
  "trust:read",
  "trust:manage",
  "products:read",
  "products:write",
  "products:publish",
  "passports:read",
  "passports:issue",
  "passports:update",
  "passports:revoke",
  "passports:recharge",
  "qr:read",
  "qr:create",
  "qr:rotate",
  "qr:suspend",
  "qr:print",
  "scans:read",
  "scans:export",
  "verify:public",
  "inventory:read",
  "inventory:adjust",
  "production:read",
  "production:write",
  "customers:read",
  "customers:write",
  "distributors:read",
  "distributors:write",
  "orders:read",
  "orders:write",
  "orders:cancel",
  "invoices:read",
  "invoices:write",
  "academy:read",
  "academy:manage",
  "expert:use_public",
  "expert:use_admin",
  "expert:tools_confirm",
  "automations:read",
  "automations:manage",
  "automations:trigger",
  "reports:read",
  "reports:run",
  "imports:run",
  "exports:run",
  "webhooks:manage",
  "notifications:read",
  "notifications:write",
  "notifications:manage",
  "dashboard:read",
  "dashboard:configure",
  "inventory:transfer",
  "batches:read",
  "batches:write",
  "reports:schedule",
  "portal:distributor",
  "portal:customer",
  "auth:login",
  "auth:manage_invites",
  "auth:reset_password",
] as const;

export type PermissionKey = (typeof PERMISSION_KEYS)[number];

export const USER_STATUSES = ["invited", "active", "disabled", "locked"] as const;
export type UserStatus = (typeof USER_STATUSES)[number];

export const MEMBERSHIP_STATUSES = ["pending", "active", "revoked"] as const;
export type MembershipStatus = (typeof MEMBERSHIP_STATUSES)[number];

export const SESSION_STATUSES = ["active", "revoked", "expired"] as const;
export type SessionStatus = (typeof SESSION_STATUSES)[number];

export const INVITATION_STATUSES = ["pending", "accepted", "revoked", "expired"] as const;
export type InvitationStatus = (typeof INVITATION_STATUSES)[number];

/** Default permission bundles for system roles (authorization still checks permissions). */
export const ROLE_PERMISSION_MAP: Record<SystemRoleKey, readonly PermissionKey[]> = {
  super_admin: PERMISSION_KEYS,
  admin: PERMISSION_KEYS.filter(
    (p) =>
      p !== "feature_flags:manage" && !p.startsWith("api_keys:") && p !== "auth:reset_password",
  ),
  production: [
    "org:read",
    "products:read",
    "passports:read",
    "passports:issue",
    "passports:update",
    "qr:read",
    "qr:create",
    "qr:rotate",
    "qr:print",
    "scans:read",
    "inventory:read",
    "inventory:adjust",
    "inventory:transfer",
    "batches:read",
    "batches:write",
    "production:read",
    "production:write",
    "dashboard:read",
    "sessions:read",
    "auth:login",
  ],
  sales: [
    "org:read",
    "users:read",
    "products:read",
    "passports:read",
    "scans:read",
    "inventory:read",
    "customers:read",
    "customers:write",
    "distributors:read",
    "distributors:write",
    "orders:read",
    "orders:write",
    "orders:cancel",
    "academy:read",
    "expert:use_admin",
    "reports:read",
    "reports:run",
    "dashboard:read",
    "notifications:read",
    "sessions:read",
    "auth:login",
  ],
  distributor: [
    "products:read",
    "passports:read",
    "verify:public",
    "orders:read",
    "orders:write",
    "academy:read",
    "expert:use_public",
    "portal:distributor",
    "sessions:read",
    "auth:login",
  ],
  customer: [
    "passports:read",
    "verify:public",
    "orders:read",
    "academy:read",
    "expert:use_public",
    "portal:customer",
    "sessions:read",
    "auth:login",
  ],
  guest: ["verify:public", "expert:use_public", "products:read"],
  service: [
    "scans:read",
    "passports:read",
    "passports:update",
    "qr:read",
    "automations:trigger",
    "notifications:read",
  ],
};
